/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as ConfigurationRouteImport } from './routes/configuration'
import { Route as AppliedRouteImport } from './routes/applied'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurationRoute = ConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => rootRouteImport,
} as any)
const AppliedRoute = AppliedRouteImport.update({
  id: '/applied',
  path: '/applied',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applied': typeof AppliedRoute
  '/configuration': typeof ConfigurationRoute
  '/jobs': typeof JobsRoute
  '/logs': typeof LogsRoute
  '/plan': typeof PlanRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applied': typeof AppliedRoute
  '/configuration': typeof ConfigurationRoute
  '/jobs': typeof JobsRoute
  '/logs': typeof LogsRoute
  '/plan': typeof PlanRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applied': typeof AppliedRoute
  '/configuration': typeof ConfigurationRoute
  '/jobs': typeof JobsRoute
  '/logs': typeof LogsRoute
  '/plan': typeof PlanRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applied'
    | '/configuration'
    | '/jobs'
    | '/logs'
    | '/plan'
    | '/profile'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applied'
    | '/configuration'
    | '/jobs'
    | '/logs'
    | '/plan'
    | '/profile'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/applied'
    | '/configuration'
    | '/jobs'
    | '/logs'
    | '/plan'
    | '/profile'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppliedRoute: typeof AppliedRoute
  ConfigurationRoute: typeof ConfigurationRoute
  JobsRoute: typeof JobsRoute
  LogsRoute: typeof LogsRoute
  PlanRoute: typeof PlanRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuration': {
      id: '/configuration'
      path: '/configuration'
      fullPath: '/configuration'
      preLoaderRoute: typeof ConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applied': {
      id: '/applied'
      path: '/applied'
      fullPath: '/applied'
      preLoaderRoute: typeof AppliedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppliedRoute: AppliedRoute,
  ConfigurationRoute: ConfigurationRoute,
  JobsRoute: JobsRoute,
  LogsRoute: LogsRoute,
  PlanRoute: PlanRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
